# AILang Developer Experience Tool: ail static_analyzer
# Static code analyzer wrapper - orchestrates the AILang analyzer

"""AILang Static Analyzer wrapper - discovers .ail files, runs analyzer, produces reports."""

import json
import subprocess
import sys
from pathlib import Path

from ail_platform.project import get_project_root
from ail_platform.report_schema import ExitCode


def discover_ail_files(target: Path) -> list[Path]:
    """Discover all .ail files from the given target (file, directory, or '.')."""
    # First handle file input
    if target.is_file() and str(target).endswith(".ail"):
        return [target]

    if target.is_dir():
        # Single pattern, then deduplicate and exclude
        raw_files = list(target.rglob("*.ail"))
        # Exclude patterns
        exclude_dirs = {
            ".venv",
            ".venv_test",
            ".git",
            "__pycache__",
            "ailang.egg-info",
            "generated",
        }
        filtered = [
            f for f in raw_files if not any(excl in f.parts for excl in exclude_dirs)
        ]
        return sorted(set(filtered))

    return []


def run_analyzer_on_file(filepath: Path, timeout: int = 300) -> tuple[dict, str]:
    """Run the AILang static analyzer on a single file and return parsed results."""
    root = get_project_root()
    analyzer_app = root / "apps" / "static_analyzer" / "main.ail"
    result = subprocess.run(
        [sys.executable, "-m", "compiler", str(analyzer_app), str(filepath)],
        capture_output=True,
        text=True,
        cwd=root,
        timeout=timeout,
    )

    # Parse stdout to extract metrics
    output = result.stdout
    metrics = {
        "path": str(filepath),
        "total_lines": 0,
        "functions": 0,
        "unreachable_functions": [],
        "undocumented_functions": [],
        "max_depth": 0,
        "recursive_functions": [],
        "unused_functions": [],
    }

    # Parse key metrics from output
    for line in output.split("\n"):
        if "Total lines:" in line:
            try:
                metrics["total_lines"] = int(line.split(":")[1].strip())
            except (ValueError, IndexError):
                pass
        elif "Total functions:" in line:
            try:
                metrics["functions"] = int(line.split(":")[1].strip())
            except (ValueError, IndexError):
                pass
        elif "Max call depth:" in line:
            try:
                metrics["max_depth"] = int(line.split(":")[1].strip())
            except (ValueError, IndexError):
                pass
        elif "Unreachable fns:" in line and "(none)" not in line:
            # Parse: "  Unreachable fns:  func1, func2"
            parts = line.split(":", 1)
            if len(parts) > 1:
                funcs = parts[1].strip()
                if funcs and funcs != "(none)":
                    metrics["unreachable_functions"] = [
                        f.strip() for f in funcs.split(",")
                    ]
        elif "Missing docs:" in line and "(none)" not in line:
            parts = line.split(":", 1)
            if len(parts) > 1:
                funcs = parts[1].strip()
                if funcs and funcs != "(none)":
                    metrics["undocumented_functions"] = [
                        f.strip() for f in funcs.split(",")
                    ]
        elif "Recursive:" in line and "(none detected)" not in line:
            parts = line.split(":", 1)
            if len(parts) > 1:
                funcs = parts[1].strip()
                if funcs and funcs != "(none)":
                    metrics["recursive_functions"] = [
                        f.strip() for f in funcs.split(",")
                    ]
        elif "Unused functions:" in line and "(none)" not in line:
            parts = line.split(":", 1)
            if len(parts) > 1:
                funcs = parts[1].strip()
                if funcs and funcs != "(none)":
                    metrics["unused_functions"] = [f.strip() for f in funcs.split(",")]

    return metrics, output


def generate_markdown_report(
    results: list[dict], raw_outputs: list[str], thresholds: dict
) -> str:
    """Generate a markdown report from the analysis results."""
    lines = [
        "# AILang Static Analyzer Report",
        "",
        "_Auto-generated by `ail static_analyzer` tool_",
        "",
    ]

    # Aggregate metrics
    total_files = len(results)
    total_lines = sum(r["total_lines"] for r in results)
    total_functions = sum(r["functions"] for r in results)
    total_unreachable = sum(len(r["unreachable_functions"]) for r in results)
    total_undocumented = sum(len(r["undocumented_functions"]) for r in results)
    max_depth = max((r["max_depth"] for r in results), default=0)

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Files analyzed**: {total_files}")
    lines.append(f"- **Total lines**: {total_lines}")
    lines.append(f"- **Total functions**: {total_functions}")
    lines.append(f"- **Max call depth**: {max_depth}")
    lines.append(f"- **Unreachable functions**: {total_unreachable}")
    lines.append(f"- **Undocumented functions**: {total_undocumented}")
    lines.append("")

    # Warnings section
    warnings = []
    large_files = [
        r for r in results if r["total_lines"] > thresholds["large_file_threshold"]
    ]
    many_funcs = [
        r for r in results if r["functions"] > thresholds["many_functions_threshold"]
    ]
    deep_recursion = [r for r in results if r["max_depth"] > thresholds["max_depth"]]

    if large_files:
        warnings.append("### Large Files")
        for r in large_files:
            warnings.append(
                f"- `{r['path']}`: {r['total_lines']} lines (threshold: {thresholds['large_file_threshold']})"
            )
        warnings.append("")

    if many_funcs:
        warnings.append("### Many Functions")
        for r in many_funcs:
            warnings.append(
                f"- `{r['path']}`: {r['functions']} functions (threshold: {thresholds['many_functions_threshold']})"
            )
        warnings.append("")

    if deep_recursion:
        warnings.append("### Deep Recursion")
        for r in deep_recursion:
            warnings.append(
                f"- `{r['path']}`: max depth {r['max_depth']} (threshold: {thresholds['max_depth']})"
            )
        warnings.append("")

    if warnings:
        lines.append("## Warnings")
        lines.extend(warnings)

    # Details section
    lines.append("## File Details")
    lines.append("")
    for i, r in enumerate(results):
        lines.append(f"### {r['path']}")
        lines.append("")
        lines.append(f"- Lines: {r['total_lines']}")
        lines.append(f"- Functions: {r['functions']}")
        if r["unreachable_functions"]:
            lines.append(f"- Unreachable: {', '.join(r['unreachable_functions'])}")
        if r["undocumented_functions"]:
            lines.append(f"- Undocumented: {', '.join(r['undocumented_functions'])}")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    """Main entry point for the ail static_analyzer tool."""
    import argparse

    parser = argparse.ArgumentParser(
        description="AILang Static Analyzer - analyzes .ail source files"
    )
    parser.add_argument(
        "target",
        nargs="?",
        default=".",
        help="File or directory to analyze (.ail file, directory, or '.')",
    )
    parser.add_argument(
        "--json-only", action="store_true", help="Output only JSON report"
    )
    parser.add_argument(
        "--markdown-only", action="store_true", help="Output only markdown report"
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=10,
        help="Maximum recursion depth warning threshold (default: 10)",
    )
    parser.add_argument(
        "--large-file-threshold",
        type=int,
        default=1000,
        help="Large file warning threshold in lines (default: 1000)",
    )
    parser.add_argument(
        "--many-functions-threshold",
        type=int,
        default=100,
        help="Many functions warning threshold (default: 100)",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=300,
        help="Subprocess timeout in seconds per file (default: 300)",
    )
    args = parser.parse_args()

    root = get_project_root()

    # Determine what to analyze
    target_path = Path(args.target)
    if not target_path.is_absolute():
        target_path = root / target_path

    ail_files = discover_ail_files(target_path)

    if not ail_files:
        print(f"Error: No .ail files found in {target_path}", file=sys.stderr)
        return ExitCode.FAILURE

    thresholds = {
        "max_depth": args.max_depth,
        "large_file_threshold": args.large_file_threshold,
        "many_functions_threshold": args.many_functions_threshold,
    }

    results = []
    raw_outputs = []
    for ail_file in ail_files:
        metrics, raw = run_analyzer_on_file(ail_file, args.timeout)
        results.append(metrics)
        raw_outputs.append(raw)
        print(f"Analyzed: {ail_file}")

    json_output = json.dumps(results, indent=2)
    markdown_output = generate_markdown_report(results, raw_outputs, thresholds)

    output_dir = root / "generated"
    output_dir.mkdir(parents=True, exist_ok=True)

    json_path = output_dir / "STATIC_ANALYZER_REPORT.json"
    md_path = output_dir / "STATIC_ANALYZER_REPORT.md"

    exit_code = ExitCode.SUCCESS

    if any(r["total_lines"] > thresholds["large_file_threshold"] for r in results):
        exit_code = ExitCode.FAILURE
    if any(r["functions"] > thresholds["many_functions_threshold"] for r in results):
        exit_code = ExitCode.FAILURE

    if not args.json_only:
        md_path.write_text(markdown_output, encoding="utf-8")
        print(f"\nGenerated: {md_path}")

    if not args.markdown_only:
        json_path.write_text(json_output, encoding="utf-8")
        print(f"Generated: {json_path}")

    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
