# DX Tool #004 AI Validation
# Validates that the benchmark output is correctly structured
# for AI consumption -- deterministic schema, clear fields,
# self-contained reports.

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path


def run_command(cmd: list[str]) -> tuple[int, str, str]:
    """Run a command and return exit code, stdout, stderr."""
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode, result.stdout, result.stderr


def clean_benchmark_outputs():
    """Remove generated benchmark outputs."""
    root = Path(__file__).resolve().parent.parent
    bench_dir = root / "generated" / "benchmarks"
    if bench_dir.exists():
        shutil.rmtree(bench_dir)


def validate_json_schema() -> bool:
    """Test: JSON schema is AI-consumable with predictable fields."""
    print("TEST 1: JSON schema validation...")
    root = Path(__file__).resolve().parent.parent
    clean_benchmark_outputs()

    code, out, err = run_command(
        [
            sys.executable,
            "-m",
            "tools.ail_benchmark",
            "--suite",
            "quick",
            "--repeat",
            "1",
            "--quiet",
        ]
    )
    if code != 0:
        print(f"  [FAIL] FAIL: Tool exited with {code}")
        return False

    json_path = root / "generated" / "benchmarks" / "BENCHMARK_REPORT.json"
    data = json.loads(json_path.read_text(encoding="utf-8"))

    checks = []

    # Schema version
    if data.get("version") == "0.1.0":
        checks.append("[PASS] Schema version present")
    else:
        checks.append("[FAIL] Schema version missing/wrong")

    # All benchmark names are strings
    all_names_str = all(isinstance(b.get("name"), str) for b in data["benchmarks"])
    checks.append(
        "[PASS] All benchmark names are strings"
        if all_names_str
        else "[FAIL] Benchmark names not strings"
    )

    # All statuses are valid
    valid_statuses = {"pass", "fail", "skip"}
    all_status_valid = all(
        b.get("status") in valid_statuses for b in data["benchmarks"]
    )
    checks.append(
        "[PASS] All statuses valid"
        if all_status_valid
        else "[FAIL] Invalid status found"
    )

    # Stats have all 4 fields (min, max, avg, median)
    stat_fields = {"min", "max", "avg", "median"}
    for b in data["benchmarks"]:
        bt = b.get("stats", {}).get("build_time", {})
        rt = b.get("stats", {}).get("run_time", {})
        if not stat_fields.issubset(bt.keys()) or not stat_fields.issubset(rt.keys()):
            checks.append(f"[FAIL] Missing stat fields in {b['name']}")
            break
    else:
        checks.append("[PASS] All stat fields present (min, max, avg, median)")

    # Summary total matches benchmark count
    if data["summary"]["total"] == len(data["benchmarks"]):
        checks.append("[PASS] Summary total matches benchmark count")
    else:
        checks.append("[FAIL] Summary total mismatch")

    # Config section is self-contained
    if "repeat" in data.get("config", {}):
        checks.append("[PASS] Config section present with repeat count")
    else:
        checks.append("[FAIL] Config section missing repeat count")

    for check in checks:
        print(f"  {check}")

    return all(c.startswith("[PASS]") for c in checks)


def validate_markdown_schema() -> bool:
    """Test: Markdown output has expected sections."""
    print("\nTEST 2: Markdown schema validation...")
    root = Path(__file__).resolve().parent.parent
    md_path = root / "generated" / "benchmarks" / "BENCHMARK_REPORT.md"
    content = md_path.read_text(encoding="utf-8")

    checks = []

    # Header
    if "# AILang Benchmark Report" in content:
        checks.append("[PASS] Title header present")
    else:
        checks.append("[FAIL] Title header missing")

    # Auto-generated attribution
    if "Auto-generated by" in content and "ail benchmark" in content:
        checks.append("[PASS] Tool attribution present")
    else:
        checks.append("[FAIL] Tool attribution missing")

    # Summary section
    if "## Summary" in content:
        checks.append("[PASS] Summary section present")
    else:
        checks.append("[FAIL] Summary section missing")

    # Benchmarks table
    if "## Benchmarks" in content:
        checks.append("[PASS] Benchmarks section present")
    else:
        checks.append("[FAIL] Benchmarks section missing")

    # Run Details section
    if "## Run Details" in content:
        checks.append("[PASS] Run Details section present")
    else:
        checks.append("[FAIL] Run Details section missing")

    # Per-benchmark data
    for bm_name in ["dice_roller", "hangman_game"]:
        if bm_name in content:
            checks.append(f"[PASS] Benchmark '{bm_name}' reported")
        else:
            checks.append(f"[FAIL] Benchmark '{bm_name}' missing")

    # Footer
    if "This report was generated" in content:
        checks.append("[PASS] Footer present")
    else:
        checks.append("[FAIL] Footer missing")

    for check in checks:
        print(f"  {check}")

    return all(c.startswith("[PASS]") for c in checks)


def validate_deterministic_schema() -> bool:
    """Test: Schema is deterministic across runs."""
    print("\nTEST 3: Schema determinism...")
    root = Path(__file__).resolve().parent.parent

    # Run twice and compare structural schema
    clean_benchmark_outputs()
    run_command(
        [
            sys.executable,
            "-m",
            "tools.ail_benchmark",
            "--suite",
            "quick",
            "--repeat",
            "1",
            "--quiet",
        ]
    )
    json_path = root / "generated" / "benchmarks" / "BENCHMARK_REPORT.json"
    data1 = json.loads(json_path.read_text(encoding="utf-8"))

    clean_benchmark_outputs()
    run_command(
        [
            sys.executable,
            "-m",
            "tools.ail_benchmark",
            "--suite",
            "quick",
            "--repeat",
            "1",
            "--quiet",
        ]
    )
    data2 = json.loads(json_path.read_text(encoding="utf-8"))

    # Compare schema-level properties
    checks = []
    if sorted(data1.keys()) == sorted(data2.keys()):
        checks.append("[PASS] Top-level keys are deterministic")
    else:
        checks.append("[FAIL] Top-level keys differ")

    s1, s2 = data1["summary"], data2["summary"]
    if sorted(s1.keys()) == sorted(s2.keys()):
        checks.append("[PASS] Summary keys are deterministic")
    else:
        checks.append("[FAIL] Summary keys differ")

    names1 = [b["name"] for b in data1["benchmarks"]]
    names2 = [b["name"] for b in data2["benchmarks"]]
    if names1 == names2:
        checks.append("[PASS] Benchmark names are deterministic")
    else:
        checks.append("[FAIL] Benchmark names differ")

    # Benchmark entry structure
    if sorted(data1["benchmarks"][0].keys()) == sorted(data2["benchmarks"][0].keys()):
        checks.append("[PASS] Benchmark entry schema is deterministic")
    else:
        checks.append("[FAIL] Benchmark entry schema differs")

    for check in checks:
        print(f"  {check}")

    return all(c.startswith("[PASS]") for c in checks)


def validate_self_contained() -> bool:
    """Test: Report is self-contained (doesn't reference external files)."""
    print("\nTEST 4: Self-contained report...")
    root = Path(__file__).resolve().parent.parent
    md_path = root / "generated" / "benchmarks" / "BENCHMARK_REPORT.md"
    content = md_path.read_text(encoding="utf-8")

    checks = []
    # No external file references (relative paths)
    external_refs = ['.md"', '.json"']
    has_external = any(ref in content for ref in external_refs)
    if not has_external:
        checks.append("[PASS] Report is self-contained (no external references)")
    else:
        checks.append("[WARN] Report may contain external references")

    # All benchmark data is inline
    for bm_name in ["dice_roller", "hangman_game"]:
        if content.count(bm_name) >= 2:
            checks.append(f"[PASS] '{bm_name}' appears in multiple sections")
        else:
            checks.append(f"[WARN] '{bm_name}' appears only once")

    for check in checks:
        print(f"  {check}")

    return True


def main() -> int:
    """Run all AI validation tests."""
    print("=" * 60)
    print("DX TOOL #004 AI VALIDATION")
    print("=" * 60)

    results = {
        "JSON schema valid": validate_json_schema(),
        "Markdown schema valid": validate_markdown_schema(),
        "Schema deterministic": validate_deterministic_schema(),
        "Self-contained report": validate_self_contained(),
    }

    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)

    for name, passed in results.items():
        status = "PASS" if passed else "FAIL"
        symbol = "[PASS]" if passed else "[FAIL]"
        print(f"  {symbol} {name}: {status}")

    all_passed = all(results.values())
    print("\n" + ("ALL TESTS PASSED" if all_passed else "SOME TESTS FAILED"))

    return 0 if all_passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
