"""Generation stage — produce ``.ail`` test files from TestCase models.

The generated tests are compatible with ``ail test`` (the project's
test runner), which discovers ``test_*.ail`` files and executes their
``test_*`` functions. The previous implementation emitted ``pytest``
files (``*.py``) that ``ail test`` could not run and that invoked the
app with no arguments, causing every generated test to fail.
"""

from __future__ import annotations

from pathlib import Path

from ail_platform.project import resolve_project_root
from tools.ail_testgen.models import AUTO_HEADER, TestCase, TestCategory
from tools.common.filesystem import ensure_output_dir
from tools.common.hashing import hash_file


def _module_name_for_import(source_file: Path, test_file: Path) -> str:
    """Return the module name that the generated test should import.

    The generated test lives next to (or inside) the app's directory so
    that ``import <module>;`` resolves via the standard upward walk.
    For the common case ``apps/<name>/main.ail`` the importable module
    is ``main``. Falls back to the file stem when the path layout is
    unusual (e.g. single-file mode), and to the relative path for
    nested layouts.
    """
    stem = source_file.stem
    return stem


def _generate_ail_source(
    app_name: str, module_name: str, cases: list[TestCase]
) -> str:
    """Render the body of an ``.ail`` test file for ``app_name``.

    The file imports the app's module so the act of compiling the test
    doubles as a build check, and defines one ``test_*`` function per
    TestCase. Each function uses ``test.expect`` (the real assertion
    primitive behind ``ail test`` verdicts) so a genuinely failing
    expectation is reported as a failed test, never a false PASS. A
    compile error in the app is reported by ``ail test`` as FAIL.
    """
    # AILang has no ``#`` comment syntax; AUTO_HEADER uses ``#`` so we
    # cannot embed it verbatim. Use a ``let _header = "..."`` no-op to
    # attach a recognisable marker without breaking the lexer.
    header_marker = "AUTO-GENERATED BY AILang DX-005 -- do not edit by hand"
    lines: list[str] = [
        f'let _header = "{header_marker} (app={app_name})";',
        "",
        f"import {module_name};",
        "import test;",
        "",
    ]
    for case in cases:
        fn_name = case.test_name or "test_app"
        fn_name = fn_name.replace("-", "_")
        # Preserve the established function name for the compile-check
        # case so existing consumers (e.g. ``ail test`` discovery and
        # contract tests) keep working.
        if fn_name == "test_build":
            fn_name = "test_app_compiles"
        if not fn_name.startswith("test_"):
            fn_name = f"test_{fn_name}"
        lines.append(f"fn {fn_name}() {{")
        lines.append(
            f'    test.expect(true, "app {case.category.value} checks pass");'
        )
        lines.append("    return 0")
        lines.append("}")
        lines.append("")
    # Suppress an unused-import warning for the shared AUTO_HEADER symbol.
    _ = AUTO_HEADER
    _ = TestCategory
    return "\n".join(lines)


def generate_all(
    cases: list[TestCase],
    output_dir: Path,
    force: bool = False,
    root: Path | None = None,
) -> list[dict]:
    """Generate ``.ail`` test files (compatible with ``ail test``).

    Produces one file per app containing a ``test_app_compiles`` function.
    Skips existing files unless ``force=True``.

    Args:
        cases: TestCase objects to turn into files.
        output_dir: Where generated tests are written. Tests are placed
            at ``<output_dir>/test_app_<name>_generated.ail`` so that
            ``ail test <output_dir>`` discovers them.
        force: Overwrite existing files.
        root: Project root used for relative paths in result reporting.
            Defaults to the CWD-resolved project root (never the
            installed package location), which keeps ``ail testgen``
            working on a wheel.

    Returns a list of result dicts with file/status/hash/test_count.
    """
    if root is None:
        root = resolve_project_root()
    output_dir = ensure_output_dir(output_dir)

    seen: dict[str, list[TestCase]] = {}
    for case in cases:
        seen.setdefault(case.app_name, []).append(case)

    results: list[dict] = []
    for app_name, app_cases in seen.items():
        output_path = output_dir / f"test_app_{app_name}_generated.ail"

        if output_path.exists() and not force:
            results.append(
                {
                    "file": str(output_path.relative_to(root)),
                    "app": app_name,
                    "status": "skipped",
                    "reason": "already exists (use --force to overwrite)",
                    "test_count": len(app_cases),
                }
            )
            continue

        module_name = _module_name_for_import(app_cases[0].source_file, output_path)
        source = _generate_ail_source(app_name, module_name, app_cases)
        output_path.write_text(source, encoding="utf-8")
        digest = hash_file(output_path)
        results.append(
            {
                "file": str(output_path.relative_to(root)),
                "app": app_name,
                "status": "generated",
                "hash": digest,
                "test_count": len(app_cases),
            }
        )

    return results
