"""Data models for DX-005 Test Generator."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any


class TestCategory(Enum):
    BUILD = "build"
    RUN = "run"
    UNIT = "unit"
    INTEGRATION = "integration"


@dataclass
class AppInfo:
    name: str
    source_file: Path
    line_count: int = 0


@dataclass
class TestCase:
    app_name: str
    source_file: Path
    category: TestCategory
    test_name: str
    description: str = ""
    inputs: list[str] | None = None
    expected_exit_code: int = 0
    expected_output_contains: list[str] | None = None


@dataclass
class CoverageReport:
    apps_total: int
    apps_with_tests: int
    apps_without_tests: int
    untested_apps: list[str]
    coverage_pct: float


AUTO_HEADER = """# -----------------------------------------------------------------------------
# AUTO-GENERATED BY AILang DX-005
#
# This file may be regenerated.
#
# Manual edits may be overwritten.
# -----------------------------------------------------------------------------

"""
