from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path


class ExitCode:
    """Standard exit codes for all DX tools.

    All tools should use these constants instead of hardcoded integers.
    """

    SUCCESS = 0
    FAILURE = 1
    REGRESSION = 2
    INTERNAL_ERROR = 3

    # Package manager specific codes (M77.1)
    RESOLUTION_FAILURE = 1
    CIRCULAR_DEPENDENCY = 2
    INVALID_MANIFEST = 3
    LOCKFILE_MISMATCH = 4
    GIT_CLONE_FAILURE = 5


@dataclass
class ReportMetadata:
    tool: str
    version: str
    timestamp: str = ""

    def __post_init__(self) -> None:
        if not self.timestamp:
            self.timestamp = datetime.now(UTC).isoformat()

    def to_dict(self) -> dict:
        return {
            "tool": self.tool,
            "version": self.version,
            "timestamp": self.timestamp,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ReportMetadata:
        return cls(
            tool=data.get("tool", ""),
            version=data.get("version", ""),
            timestamp=data.get("timestamp", ""),
        )


@dataclass
class ReportSummary:
    total: int = 0
    passed: int = 0
    failed: int = 0
    skipped: int = 0

    def to_dict(self) -> dict:
        return {
            "total": self.total,
            "passed": self.passed,
            "failed": self.failed,
            "skipped": self.skipped,
        }

    @classmethod
    def from_dict(cls, data: dict) -> ReportSummary:
        return cls(
            total=data.get("total", 0),
            passed=data.get("passed", 0),
            failed=data.get("failed", 0),
            skipped=data.get("skipped", 0),
        )


@dataclass
class Report:
    metadata: ReportMetadata
    summary: ReportSummary
    payload: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "metadata": self.metadata.to_dict(),
            "summary": self.summary.to_dict(),
            **self.payload,
        }

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, default=str)

    def to_markdown(self) -> str:
        lines: list[str] = []
        lines.append(f"# {self.metadata.tool.replace('_', ' ').title()} Report")
        lines.append("")
        lines.append(f"_Auto-generated by `{self.metadata.tool}` tool_")
        lines.append("")
        lines.append(f"**Version:** {self.metadata.version}")
        lines.append(f"**Timestamp:** {self.metadata.timestamp}")
        lines.append("")
        lines.append("## Summary")
        lines.append("")
        lines.append(f"- **Total:** {self.summary.total}")
        lines.append(f"- **Passed:** {self.summary.passed}")
        lines.append(f"- **Failed:** {self.summary.failed}")
        lines.append(f"- **Skipped:** {self.summary.skipped}")
        lines.append("")
        return "\n".join(lines)


def write_report(
    report: Report, output_dir: Path, formats: set[str] | None = None
) -> dict[str, Path]:
    """Write report in specified formats.

    Args:
        report: The report to write.
        output_dir: Directory to write into.
        formats: Set of "json" and/or "markdown". Defaults to both.

    Returns:
        Dict mapping format name to written Path.
    """
    if formats is None:
        formats = {"json", "markdown"}
    output_dir.mkdir(parents=True, exist_ok=True)
    result: dict[str, Path] = {}

    if "json" in formats:
        json_path = output_dir / f"{report.metadata.tool.upper()}_REPORT.json"
        json_path.write_text(report.to_json(), encoding="utf-8")
        result["json"] = json_path

    if "markdown" in formats:
        md_path = output_dir / f"{report.metadata.tool.upper()}_REPORT.md"
        md_path.write_text(report.to_markdown(), encoding="utf-8")
        result["markdown"] = md_path

    return result
