"""AILang Dependency Ordering Assistant - Report generation."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from tools.ail_order.models import FileAnalysis, ProjectAnalysis, OrderingFinding, Severity


def generate_markdown_report(analysis: ProjectAnalysis | FileAnalysis) -> str:
    """Generate a Markdown report from analysis results."""
    lines = [
        "# Dependency Order Analysis Report",
        "",
        "_Auto-generated by `ail order` tool_",
        "",
    ]
    
    if isinstance(analysis, ProjectAnalysis):
        _generate_project_report(lines, analysis)
    else:
        _generate_single_file_report(lines, analysis)
    
    return "\n".join(lines)


def _generate_project_report(lines: list[str], analysis: ProjectAnalysis) -> None:
    """Generate report for project analysis."""
    lines.append("## Project Summary")
    lines.append("")
    lines.append(f"- **Files analyzed**: {len(analysis.files)}")
    lines.append(f"- **Total functions**: {analysis.total_functions}")
    lines.append(f"- **Total findings**: {analysis.total_findings}")
    lines.append(f"- **Total cycles**: {analysis.total_cycles}")
    lines.append("")
    
    # Aggregate findings
    errors = []
    warnings = []
    recommendations = []
    
    for file_analysis in analysis.files:
        for finding in file_analysis.findings:
            if finding.severity == Severity.ERROR:
                errors.append((file_analysis.path, finding))
            elif finding.severity == Severity.WARNING:
                warnings.append((file_analysis.path, finding))
    
    if errors:
        lines.append("## Errors")
        lines.append("")
        for path, finding in errors:
            lines.append(f"- `{path}`: {finding.message}")
            if finding.suggestion:
                lines.append(f"  - Suggestion: {finding.suggestion}")
        lines.append("")
    
    if warnings:
        lines.append("## Warnings")
        lines.append("")
        for path, finding in warnings:
            lines.append(f"- `{path}`: {finding.message}")
        lines.append("")
    
    lines.append("## File Details")
    lines.append("")
    
    for file_analysis in analysis.files:
        lines.append(f"### {file_analysis.path}")
        lines.append("")
        lines.append(f"- Functions: {len(file_analysis.functions)}")
        lines.append(f"- Levels: {len(file_analysis.levels)}")
        lines.append(f"- Cycles: {len(file_analysis.cycles)}")
        lines.append("")


def _generate_single_file_report(lines: list[str], analysis: FileAnalysis) -> None:
    """Generate report for a single file."""
    lines.append(f"**File:** `{analysis.path}`")
    lines.append("")
    lines.append("## Dependency Order")
    lines.append("")
    
    # Show levels
    max_level = max(analysis.levels.keys()) if analysis.levels else 0
    for level in range(max_level + 1):
        funcs = analysis.levels.get(level, [])
        lines.append(f"L{level}:")
        for func in funcs:
            lines.append(f"  - {func}")
        lines.append("")
    
    lines.append("## Findings")
    lines.append("")
    
    errors = [f for f in analysis.findings if f.severity == Severity.ERROR]
    warnings = [f for f in analysis.findings if f.severity == Severity.WARNING]
    
    if errors:
        lines.append("### Errors")
        for finding in errors:
            lines.append(f"- {finding.message}")
            if finding.suggestion:
                lines.append(f"  - Suggestion: {finding.suggestion}")
        lines.append("")
    
    if warnings:
        lines.append("### Warnings")
        for finding in warnings:
            lines.append(f"- {finding.message}")
        lines.append("")
    
    if not errors and not warnings:
        lines.append("No issues found. The file follows correct dependency ordering.")
        lines.append("")


def generate_json_report(analysis: ProjectAnalysis | FileAnalysis) -> str:
    """Generate a JSON report from analysis results."""
    if isinstance(analysis, ProjectAnalysis):
        data = _serialize_project(analysis)
    else:
        data = _serialize_file(analysis)
    
    return json.dumps(data, indent=2)


def _serialize_file(analysis: FileAnalysis) -> dict:
    """Serialize FileAnalysis to dict."""
    errors = [f for f in analysis.findings if f.severity == Severity.ERROR]
    warnings = [f for f in analysis.findings if f.severity == Severity.WARNING]
    
    return {
        "metadata": {
            "tool": "ail_order",
            "version": "0.1.0",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
        "summary": {
            "total": len(analysis.functions),
            "errors": len(errors),
            "warnings": len(warnings),
            "cycles": len(analysis.cycles),
            "unreachable": len(analysis.unreachable),
            "duplicates": len(analysis.duplicates),
        },
        "levels": analysis.levels,
        "functions": [
            {
                "name": fn.name,
                "line": fn.line,
                "level": fn.level,
                "calls": fn.calls,
            }
            for fn in analysis.functions
        ],
        "cycles": analysis.cycles,
        "unreachable": analysis.unreachable,
        "duplicates": analysis.duplicates,
        "findings": [
            {
                "severity": f.severity.value,
                "message": f.message,
                "line": f.line,
                "function": f.function,
                "suggestion": f.suggestion,
            }
            for f in analysis.findings
        ],
    }


def _serialize_project(analysis: ProjectAnalysis) -> dict:
    """Serialize ProjectAnalysis to dict."""
    total_errors = sum(len([f for f in fa.findings if f.severity == Severity.ERROR]) for fa in analysis.files)
    total_warnings = sum(len([f for f in fa.findings if f.severity == Severity.WARNING]) for fa in analysis.files)
    
    return {
        "metadata": {
            "tool": "ail_order",
            "version": "0.1.0",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        },
        "summary": {
            "total": len(analysis.files),
            "functions": analysis.total_functions,
            "errors": total_errors,
            "warnings": total_warnings,
            "cycles": analysis.total_cycles,
        },
        "files": [_serialize_file(fa) for fa in analysis.files],
    }


def write_reports(analysis: ProjectAnalysis | FileAnalysis, output_dir: Path) -> tuple[Path, Path]:
    """Write both Markdown and JSON reports."""
    output_dir.mkdir(parents=True, exist_ok=True)
    
    md_path = output_dir / "dependency_ordering.md"
    json_path = output_dir / "dependency_ordering.json"
    
    md_path.write_text(generate_markdown_report(analysis), encoding="utf-8")
    json_path.write_text(generate_json_report(analysis), encoding="utf-8")
    
    return md_path, json_path