#!/usr/bin/env python3
"""Generate compiler/_version.py from pyproject.toml.

Usage:
    python scripts/generate_version.py

This script reads the version from pyproject.toml and writes it to
compiler/_version.py. Run this after updating the version in pyproject.toml.
"""

from __future__ import annotations

import tomllib
from pathlib import Path


def main() -> None:
    """Generate version file from pyproject.toml."""
    # Find pyproject.toml
    repo_root = Path(__file__).parent.parent
    pyproject_path = repo_root / "pyproject.toml"

    if not pyproject_path.exists():
        print(f"Error: pyproject.toml not found at {pyproject_path}")
        return

    # Read version from pyproject.toml
    with open(pyproject_path, "rb") as f:
        data = tomllib.load(f)

    version = data.get("project", {}).get("version")
    if not version:
        print("Error: No version found in pyproject.toml [project] section")
        return

    # Write _version.py
    version_file = repo_root / "compiler" / "_version.py"
    content = f'"""Version module - generated by scripts/generate_version.py."""\n\n__version__ = "{version}"\n'

    version_file.write_text(content, encoding="utf-8")
    print(f"Generated {version_file} with version {version}")


if __name__ == "__main__":
    main()
