#!/usr/bin/env python3
"""Synchronize all version references from pyproject.toml.

This script reads the version from pyproject.toml and updates ALL version
references across the codebase:
- compiler/_version.py
- tools/*/__main__.py VERSION constants
- tools/*/__init__.py __version__ constants

Usage:
    python scripts/sync_versions.py [--dry-run]

Exit codes:
    0 - Success
    1 - Version mismatch detected before sync
    2 - pyproject.toml not found
"""

from __future__ import annotations

import argparse
import re
import tomllib
import sys
from pathlib import Path

TOOL_VERSION_PATTERNS = [
    (r'^VERSION\s*=\s*["\']([^"\']+)["\']', "VERSION"),
    (r'^__version__\s*=\s*["\']([^"\']+)["\']', "__version__"),
]

TOOL_FILES_TO_UPDATE = [
    "tools/ail_context/__main__.py",
    "tools/ail_doctor/__main__.py",
    "tools/ail_heal/__main__.py",
    "tools/ail_package_manager/__main__.py",
    "tools/ail_mcp/__init__.py",
    "tools/ail_mcp/server.py",
    "tools/ail_mcp/context_adapter.py",
]

README_BADGE_PATTERN = r'\[!\[Version\]\(https://img\.shields\.io/badge/version-[\d.]+-blue\)\]\(#\)'
README_BADGE_REPLACEMENT = '[![Version](https://img.shields.io/badge/version-{version}-blue)](#)'


def read_pyproject_version(repo_root: Path) -> str:
    """Read version from pyproject.toml."""
    pyproject_path = repo_root / "pyproject.toml"
    if not pyproject_path.exists():
        raise FileNotFoundError(f"pyproject.toml not found at {pyproject_path}")

    with open(pyproject_path, "rb") as f:
        data = tomllib.load(f)

    version = data.get("project", {}).get("version")
    if not version:
        raise ValueError("No version found in pyproject.toml [project] section")

    return version


def update_file_version(file_path: Path, version: str, dry_run: bool = False) -> bool:
    """Update version references in a file. Returns True if changed."""
    if not file_path.exists():
        return False

    content = file_path.read_text(encoding="utf-8")
    original_content = content
    changed = False

    for pattern, _ in TOOL_VERSION_PATTERNS:
        regex = re.compile(pattern, re.MULTILINE)
        match = regex.search(content)
        if match:
            current_version = match.group(1)
            if current_version != version:
                content = regex.sub(f'\\1 = "{version}"', content, count=1)
                changed = True
                print(f"  {file_path}: {current_version} -> {version}")

    if changed and not dry_run:
        file_path.write_text(content, encoding="utf-8")

    return changed


def update_readme_badge(repo_root: Path, version: str, dry_run: bool = False) -> bool:
    """Update README.md version badge."""
    readme_path = repo_root / "README.md"
    if not readme_path.exists():
        return False

    content = readme_path.read_text(encoding="utf-8")
    new_badge = README_BADGE_REPLACEMENT.format(version=version)

    if new_badge in content:
        return False

    regex = re.compile(README_BADGE_PATTERN)
    if regex.search(content):
        content = regex.sub(new_badge, content)
        if not dry_run:
            readme_path.write_text(content, encoding="utf-8")
        return True

    return False


def sync_compiler_version(repo_root: Path, version: str, dry_run: bool = False) -> bool:
    """Sync compiler/_version.py from pyproject.toml."""
    version_file = repo_root / "compiler" / "_version.py"
    expected_content = f'"""Version module - generated by scripts/generate_version.py."""\n\n__version__ = "{version}"\n'

    if version_file.exists():
        current = version_file.read_text(encoding="utf-8")
        if current == expected_content:
            return False

    if not dry_run:
        version_file.write_text(expected_content, encoding="utf-8")
    return True


def verify_versions(repo_root: Path) -> bool:
    """Verify all version references match pyproject.toml."""
    pyproject_version = read_pyproject_version(repo_root)
    all_ok = True

    # Check compiler/_version.py
    version_file = repo_root / "compiler" / "_version.py"
    if version_file.exists():
        content = version_file.read_text(encoding="utf-8")
        match = re.search(r'__version__\s*=\s*["\']([^"\']+)["\']', content)
        if match and match.group(1) != pyproject_version:
            print(f"ERROR: {version_file} has {match.group(1)}, expected {pyproject_version}")
            all_ok = False

    # Check tool files
    for tool_file in TOOL_FILES_TO_UPDATE:
        file_path = repo_root / tool_file
        if file_path.exists():
            content = file_path.read_text(encoding="utf-8")
            for pattern, _ in TOOL_VERSION_PATTERNS:
                regex = re.compile(pattern, re.MULTILINE)
                for match in regex.finditer(content):
                    tool_version = match.group(1)
                    if tool_version != pyproject_version:
                        print(f"ERROR: {file_path} has {tool_version}, expected {pyproject_version}")
                        all_ok = False

    return all_ok


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize all version references")
    parser.add_argument("--dry-run", action="store_true", help="Show what would change without changing")
    args = parser.parse_args()

    repo_root = Path(__file__).parent.parent

    try:
        version = read_pyproject_version(repo_root)
    except FileNotFoundError:
        print(f"Error: {e}")
        return 2
    except ValueError as e:
        print(f"Error: {e}")
        return 1

    print(f"Synchronizing all versions to {version}")

    # Sync compiler/_version.py
    sync_compiler_version(repo_root, version, args.dry_run)

    # Sync tool files
    for tool_file in TOOL_FILES_TO_UPDATE:
        file_path = repo_root / tool_file
        if file_path.exists():
            changed = update_file_version(file_path, version, args.dry_run)

    # Update README badge
    if update_readme_badge(repo_root, version, args.dry_run):
        print(f"  README.md: updated badge to {version}")

    # Verify all versions match
    if not args.dry_run:
        print("\nVerifying all versions match...")
        if not verify_versions(repo_root):
            print("\nERROR: Version verification failed!")
            return 1
        print(f"\nAll versions synchronized to {version}")
    else:
        print("\n[Dry run] - no changes made")

    return 0


if __name__ == "__main__":
    sys.exit(main())