# AILang Developer Experience Tool: ail validate
# M86.5E — Validation Automation Pipeline

"""AILang Validation Pipeline — runs all quality checks and generates reports.

Verifies:
  - Documentation integrity
  - Standard library health
  - Release readiness
  - Developer experience
  - Example validity
  - Template currency

Generates machine-readable reports and a unified validation summary.
"""

import argparse
import json
import sys
import time
from pathlib import Path


def _find_root() -> Path:
    """Find the AILang repository root."""
    candidate = Path(__file__).resolve().parent.parent.parent
    if (candidate / "pyproject.toml").is_file():
        return candidate
    return Path.cwd()


def _run_check(name: str, check_fn, root: Path) -> dict:
    """Run a validation check and return standardized results."""
    start = time.time()
    try:
        report_text, json_data = check_fn(root)
        elapsed = time.time() - start
        return {
            "name": name,
            "passed": json_data.get("summary", {}).get("passed", False),
            "issues": json_data.get("summary", {}).get("total_issues", 0),
            "elapsed_seconds": round(elapsed, 2),
            "json_data": json_data,
            "report_text": report_text,
        }
    except Exception as e:
        elapsed = time.time() - start
        return {
            "name": name,
            "passed": False,
            "issues": -1,
            "elapsed_seconds": round(elapsed, 2),
            "error": str(e),
            "json_data": {},
            "report_text": f"Error: {e}",
        }


def run_pipeline(root: Path | None = None) -> tuple[str, dict]:
    """Run the full validation pipeline.

    Returns (unified_markdown_report, unified_json_data).
    """
    if root is None:
        root = _find_root()

    from tools.ail_doc_verify.__main__ import generate_report as doc_verify_report
    from tools.ail_stdlib_audit.__main__ import generate_report as stdlib_audit_report
    from tools.ail_release_verify.__main__ import generate_report as release_verify_report
    from tools.ail_dx_audit.__main__ import generate_report as dx_audit_report

    checks = [
        ("Documentation Verification", doc_verify_report),
        ("Standard Library Audit", stdlib_audit_report),
        ("Release Verification", release_verify_report),
        ("Developer Experience Audit", dx_audit_report),
    ]

    results = []
    for name, check_fn in checks:
        result = _run_check(name, check_fn, root)
        results.append(result)

    overall_passed = all(r["passed"] for r in results)
    total_issues = sum(r["issues"] for r in results if r["issues"] >= 0)
    total_elapsed = sum(r["elapsed_seconds"] for r in results)

    json_data = {
        "tool": "ail validate",
        "version": "1.0.0",
        "root": str(root),
        "summary": {
            "overall_passed": overall_passed,
            "checks_run": len(results),
            "checks_passed": sum(1 for r in results if r["passed"]),
            "checks_failed": sum(1 for r in results if not r["passed"]),
            "total_issues": total_issues,
            "total_elapsed_seconds": round(total_elapsed, 2),
        },
        "checks": [],
    }

    for r in results:
        check_entry = {
            "name": r["name"],
            "passed": r["passed"],
            "issues": r["issues"],
            "elapsed_seconds": r["elapsed_seconds"],
        }
        if "error" in r:
            check_entry["error"] = r["error"]
        json_data["checks"].append(check_entry)

    status_icon = lambda ok: "PASS" if ok else "FAIL"

    lines = [
        "# Validation Pipeline Report",
        "",
        "_Generated by `ail validate`_",
        "",
        "## Pipeline Summary",
        "",
        f"| Check | Status | Issues | Time |",
        f"|-------|--------|--------|------|",
    ]

    for r in results:
        status = status_icon(r["passed"])
        issues_str = str(r["issues"]) if r["issues"] >= 0 else "ERROR"
        elapsed = f"{r['elapsed_seconds']}s"
        lines.append(f"| {r['name']} | {status} | {issues_str} | {elapsed} |")

    lines.extend([
        f"| **Overall** | **{status_icon(overall_passed)}** | **{total_issues}** | **{round(total_elapsed, 2)}s** |",
        "",
    ])

    if overall_passed:
        lines.append("**All validation checks passed.**")
    else:
        lines.append("**Some validation checks failed.** Review individual reports for details.")
    lines.append("")

    for r in results:
        if not r["passed"]:
            lines.extend([f"## {r['name']}", ""])
            if "error" in r:
                lines.append(f"Error: {r['error']}")
            else:
                lines.append(f"Issues: {r['issues']}")
                lines.append("")
                report_lines = r["report_text"].split("\n")
                for line in report_lines[:50]:
                    lines.append(f"  {line}")
                if len(report_lines) > 50:
                    lines.append(f"  ... ({len(report_lines) - 50} more lines)")
            lines.append("")

    lines.extend([
        "---",
        "_Report generated by `ail validate`_",
        "",
    ])

    return "\n".join(lines), json_data


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="ail validate",
        description="AILang Validation Pipeline — run all quality checks",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output machine-readable JSON",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=None,
        help="Write individual reports to directory",
    )
    parser.add_argument(
        "--root",
        type=str,
        default=None,
        help="Repository root directory",
    )

    args = parser.parse_args()
    root = Path(args.root) if args.root else None

    report, json_data = run_pipeline(root)

    if args.output_dir:
        out_dir = Path(args.output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        summary_path = out_dir / "VALIDATION_PIPELINE_REPORT.md"
        summary_path.write_text(report, encoding="utf-8")

        json_path = out_dir / "validation_pipeline.json"
        json_path.write_text(json.dumps(json_data, indent=2), encoding="utf-8")

        print(f"Reports written to {out_dir}/")
        print(f"  - VALIDATION_PIPELINE_REPORT.md")
        print(f"  - validation_pipeline.json")
    elif args.json:
        print(json.dumps(json_data, indent=2))
    else:
        print(report)

    return 0 if json_data["summary"]["overall_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
